from .invoice_extraction import INVOICE_SCHEMA, INVOICE_INSTRUCTION_RU as INSTRUCTION_INVOICE
from .pl_extraction import PACKING_LIST_SCHEMA, PL_INSTRUCTION_RU as INSTRUCTION_PL
from .CMR_extraction import CMR_SCHEMA, CMR_INSTRUCTION_RU as CMR_INSTRUCTION
from .agreement_extraction import AGREEMENT_SCHEMA, AGREEMENT_INSTRUCTION_RU as AGREEMENT_INSTRUCTION
from .DT_extraction import HS_SCHEMA, DT_INSTRUCTION_RU as DT_INSTRUCTION

__all__ = [
    INVOICE_SCHEMA, INSTRUCTION_INVOICE,
    PACKING_LIST_SCHEMA, INSTRUCTION_PL,
    CMR_SCHEMA, CMR_INSTRUCTION, 
    AGREEMENT_SCHEMA, AGREEMENT_INSTRUCTION, 
    HS_SCHEMA, DT_INSTRUCTION
]